---
title: "Development of TESLA Stock: Preprocessing"
author: "Danila Kramarenko"
date: "2022-02-28 (updated: `r Sys.Date()`)"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: no
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Background

<Add five to ten sentences about the study and goals of analysis.>

# Setup

```{r}
library(tidyverse)
library(readxl)   # this package allows us to read xlsx files
library(lubridate)

library(summarytools) # dfSummary(), descr(), freq()
```

# Read the data

```{r}
dat_w <- read_csv("data/Kramarenko_1_TSLA.csv")
dat_w
```

# Preprocessing

```{r}
#view(dfSummary(dat_w))

descr(dat_w, stats="common")  
descr(dat_w, stats="fivenum")
```

Transform the data from wide to long format. 

```{r}
dat <- dat_w |> pivot_longer(2:5, names_to="StockStatistic", values_to="Price")
dat
```

# Graph

```{r}
dat |> 
  filter(StockStatistic %in% c("Low", "High") & Date < "2013-01-01") |> 
  ggplot(aes(x=Date, y=Price, group=StockStatistic, color=StockStatistic)) +
  geom_smooth() +
  scale_x_date("", date_breaks = "1 year", date_minor_breaks= "3 months", date_labels= "%Y-%m") +
  scale_y_log10("Price") +
  scale_color_manual("Stock statistic", values=c(  "green", "red")) +
  theme_bw(base_size=14)
```

# Statistic

```{r}
cor(dat_w[2:7])
```

The high correlations are spuriously high due to the change in stocks over years. We could try to remove the overall trend and check the correlations then.

# Appendix

This command ensures that somebody at some later time can reproduce your analysis.

```{r}
sessionInfo()
```